// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace financecalculator {
	public class FinanceCalculator : global::haxe.lang.HxObject {
		
		static FinanceCalculator() {
			unchecked{
				#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{530154542, 957002115, 1580406414}, new string[]{"futureValue", "registerMyMethods", "totalInterest"});
			}
		}
		#line default
		
		public FinanceCalculator(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public FinanceCalculator(global::maglev.MagLev maglev) {
			#line 12 "/my-component/src/financecalculator/FinanceCalculator.hx"
			global::financecalculator.FinanceCalculator.__hx_ctor_financecalculator_FinanceCalculator(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_financecalculator_FinanceCalculator(global::financecalculator.FinanceCalculator __hx_this, global::maglev.MagLev maglev) {
			#line 13 "/my-component/src/financecalculator/FinanceCalculator.hx"
			__hx_this.maglev = maglev;
			__hx_this.calc = new global::financecalculator.FinCalc();
			#line 15 "/my-component/src/financecalculator/FinanceCalculator.hx"
			__hx_this.registerMyMethods();
		}
		#line default
		
		public global::maglev.MagLev maglev;
		
		public global::financecalculator.FinCalc calc;
		
		public virtual void registerMyMethods() {
			#line 18 "/my-component/src/financecalculator/FinanceCalculator.hx"
			global::financecalculator.FinanceCalculator _gthis = this;
			global::maglev.MagLev bus = this.maglev;
			#line 21 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.maglev.register("FinanceCalculator.PresentValueOfFutureMoney", global::maglev.MagLevFunction.fromFunction(new global::financecalculator.FinanceCalculator_registerMyMethods_21__Fun(bus)));
			#line 32 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.maglev.register("FinanceCalculator.PresentValueOfDeposits", global::maglev.MagLevFunction.fromFunction(new global::financecalculator.FinanceCalculator_registerMyMethods_32__Fun(bus)));
			#line 43 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.maglev.register("FinanceCalculator.FutureValue", global::maglev.MagLevFunction.fromFunction(new global::financecalculator.FinanceCalculator_registerMyMethods_43__Fun(_gthis)));
			#line 58 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.maglev.register("FinanceCalculator.NetPresentValue", global::maglev.MagLevFunction.fromFunction(new global::financecalculator.FinanceCalculator_registerMyMethods_58__Fun(bus)));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
				switch (hash) {
					case 1102715029:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						this.calc = ((global::financecalculator.FinCalc) (@value) );
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return @value;
					}
					
					
					case 858513194:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return @value;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
				switch (hash) {
					case 957002115:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "registerMyMethods", 957002115)) );
					}
					
					
					case 1102715029:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return this.calc;
					}
					
					
					case 858513194:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
				switch (hash) {
					case 957002115:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						this.registerMyMethods();
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						break;
					}
					
					
					default:
					{
						#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
			baseArr.push("calc");
			#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
			baseArr.push("maglev");
			#line 8 "/my-component/src/financecalculator/FinanceCalculator.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace financecalculator {
	public class FinanceCalculator_registerMyMethods_21__Fun : global::haxe.lang.Function {
		
		public FinanceCalculator_registerMyMethods_21__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 21 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 21 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 23 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("FinanceCalculator.PresentValueOfFutureMoney"));
				#line 25 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("financecalculator"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 27 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'FinanceCalculator.PresentValueOfFutureMoney\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 29 "/my-component/src/financecalculator/FinanceCalculator.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace financecalculator {
	public class FinanceCalculator_registerMyMethods_32__Fun : global::haxe.lang.Function {
		
		public FinanceCalculator_registerMyMethods_32__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 32 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 32 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 34 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("FinanceCalculator.PresentValueOfDeposits"));
				#line 36 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("financecalculator"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 38 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'FinanceCalculator.PresentValueOfDeposits\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 40 "/my-component/src/financecalculator/FinanceCalculator.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace financecalculator {
	public class FinanceCalculator_registerMyMethods_43__Fun : global::haxe.lang.Function {
		
		public FinanceCalculator_registerMyMethods_43__Fun(global::financecalculator.FinanceCalculator _gthis) : base(1, 0) {
			#line 43 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 43 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				double presentValue = (((global::maglev.MagLevNumber) (args.@get(0)) )).getFloat();
				#line 45 "/my-component/src/financecalculator/FinanceCalculator.hx"
				int numPeriods = (((global::maglev.MagLevNumber) (args.@get(1)) )).getInt();
				double interestRate = (((global::maglev.MagLevNumber) (args.@get(2)) )).getFloat();
				#line 47 "/my-component/src/financecalculator/FinanceCalculator.hx"
				int timesCompoundedPerPeriod = (((global::maglev.MagLevNumber) (args.@get(3)) )).getInt();
				double depositAmount = (((global::maglev.MagLevNumber) (args.@get(4)) )).getFloat();
				#line 49 "/my-component/src/financecalculator/FinanceCalculator.hx"
				bool depositAtBeginning = (((global::maglev.MagLevBoolean) (args.@get(5)) )).getBool();
				object ret = this._gthis.calc.futureValue(presentValue, numPeriods, interestRate, timesCompoundedPerPeriod, depositAmount, depositAtBeginning);
				#line 51 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevObject resobj = global::maglev.MagLevObject.create();
				resobj.@set("futureValue", global::maglev.MagLevNumber.fromFloat(global::haxe.lang.Runtime.getField_f(ret, "futureValue", 530154542, true)));
				#line 53 "/my-component/src/financecalculator/FinanceCalculator.hx"
				resobj.@set("totalInterest", global::maglev.MagLevNumber.fromFloat(global::haxe.lang.Runtime.getField_f(ret, "totalInterest", 1580406414, true)));
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromResult(resobj);
				#line 55 "/my-component/src/financecalculator/FinanceCalculator.hx"
				return result;
			}
			#line default
		}
		
		
		public global::financecalculator.FinanceCalculator _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace financecalculator {
	public class FinanceCalculator_registerMyMethods_58__Fun : global::haxe.lang.Function {
		
		public FinanceCalculator_registerMyMethods_58__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 58 "/my-component/src/financecalculator/FinanceCalculator.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 58 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevArray data = global::maglev.MagLevArray.create();
				#line 60 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("_not_implemented_"));
				data.push(global::maglev.MagLevString.fromString("FinanceCalculator.NetPresentValue"));
				#line 62 "/my-component/src/financecalculator/FinanceCalculator.hx"
				data.push(global::maglev.MagLevString.fromString("financecalculator"));
				this.bus.call("MindPowered.Telemetry.Send", data);
				#line 64 "/my-component/src/financecalculator/FinanceCalculator.hx"
				global::maglev.MagLevError err = global::maglev.MagLevError.create(-20000, "You are trying to use the \'FinanceCalculator.NetPresentValue\' method but it\'s not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", data);
				global::maglev.MagLevResult result = global::maglev.MagLevResult.fromError(err);
				#line 66 "/my-component/src/financecalculator/FinanceCalculator.hx"
				return result;
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}


